; LEE EL VALOR ANALOGICO EN EL PIN0 Y LO MUEVO AL PUERTO DE SALIDAS
; AUTOR: KEVIN ROJAS-2022
#include "p12f683.inc"
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_ON & _FCMEN_ON

org	    0x00
BANKSEL	    TRISIO	;VOY AL BANCO DE TRISIO
CLRF	    TRISIO	;TODOS LOS PINES COMO SALIDAS
BSF	    TRISIO,0	;PIN0 COMO ENTRADA
BANKSEL	    ANSEL	;BANCO DE ANSEL
MOVLW	    B'00000001'	;frecuencia ADC=Fosc/2, pin0 como analògico
IORWF	    ANSEL	;MUEVO EL VALOR DE W A ANSEL
BANKSEL	    ADCON0	;BANCO DE ADCON0
MOVLW	    B'00000001' 
MOVWF	    ADCON0	;Vdd Vref, AN0, On
;B7	    JUSTIFICADO A LA IZQ
;B6	    VRED=VDD
;B5,B4	    NO SE IMPLEMENTAN
;B3,B2	    CANAL 0 DEL ADC
;B1	    NO HAY CONVERSION EN PROGRESO
;B0	    ADC ACTIVADO
INICIO
BANKSEL	    ADCON0
BSF	    ADCON0,GO	;INICIA CONVERSION
BTFSC	    ADCON0,GO	;SE HA TERMINADO LA VONVERSION?
GOTO	    $-1		;NO, SALTA UNA LINEA ARRIBA
MOVF	    ADRESH,W	;LEE 8 BITS MAS SIGNIFICATIVOS
MOVWF	    GPIO	;MUEVE LOS 8 BITS A CUALQUIER REGISTRO QUE QUERAMOS
BANKSEL	    ADRESL	;ME VOY AL BANCO DE ADRESL
MOVF	    ADRESL,W	;LEE 2 BITS MENOS SIGNIFICATIVOS
GOTO	    INICIO
end

